function generateInsight() {
  const input = document.getElementById('topicInput').value;
  const loader = document.getElementById('loader');
  const output = document.getElementById('output');

  output.innerHTML = '';
  loader.classList.remove('hidden');

  fetch('https://insightsletter.onrender.com/process', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ topic: input })
  })
    .then(res => res.json())
    .then(data => {
      loader.classList.add('hidden');

      const points = data.summary
        .split('\n')
        .filter(line => line.trim() !== '')
        .map(line => `<li>${line.trim()}</li>`)
        .join('');

      output.innerHTML = `
        <div class="insight-card">
          <h3>${data.title}</h3>
          <ul>${points}</ul>
          <p><em>Generated by ${data.generated_by}</em></p>
        </div>
      `;
    })
    .catch(err => {
      loader.classList.add('hidden');
      output.innerHTML = `<p>⚠️ Error: ${err.message}</p>`;
    });
}
